---
# src: https://raw.githubusercontent.com/dj95/zjstatus/main/.github/workflows/release.yml

name: 'Build and Publish'
on:
  push:
    branches:
      - '*'
    tags:
      - 'v?[0-9]+.*'

permissions:
  contents: write

jobs:
  build-release:
    name: build-release
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: '1.81.0'
          profile: minimal
          override: true
          target: wasm32-wasip1

      - name: Build release binary
        run: cargo build --release

      - if: >
          github.ref_type == 'tag'
        name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - if: >
          github.ref_type == 'tag'
        name: Upload wasm file to release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./target/wasm32-wasip1/release/zellij-autolock.wasm
          asset_name: zellij-autolock.wasm
          asset_content_type: application/octet-stream
